### ISSUE TITLE
make json not outputting in Confluence format

### ISSUE THREAD

**Issue by spyoungtech** [Arello-Mobile/sphinx-confluence#15]
When I do `make html` the output is in the Confluence storage format. However, this is not the case for `make json`. It appears that there is no translation occurring. May be related to changes made in #12 

Making the following change to the `setup` function seems to correct this...

```
...
    if LooseVersion(sphinx.__version__) >= LooseVersion("1.4"):
        app.set_translator("html", HTMLConfluenceTranslator)
        app.set_translator('json', HTMLConfluenceTranslator) # make it work for json, too.
...
```

Although a separate issue... I also tried doing `sphinx-build -b json_conf` but got the following exception.

```
Traceback (most recent call last):
  File "/Users/spenceryoung/ISS/lib/python3.6/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Users/spenceryoung/ISS/lib/python3.6/site-packages/sphinx/application.py", line 226, in __init__
    self.builder = self.create_builder(buildername)
  File "/Users/spenceryoung/ISS/lib/python3.6/site-packages/sphinx/application.py", line 306, in create_builder
    return self.registry.create_builder(self, name)
  File "/Users/spenceryoung/ISS/lib/python3.6/site-packages/sphinx/registry.py", line 82, in create_builder
    return self.builders[name](app)
  File "/Users/spenceryoung/ISS/lib/python3.6/site-packages/sphinx_confluence/__init__.py", line 59, in __init__
    self.translator_class = HTMLConfluenceTranslator
AttributeError: can't set attribute

Exception occurred:
  File "/Users/spenceryoung/ISS/lib/python3.6/site-packages/sphinx_confluence/__init__.py", line 59, in __init__
    self.translator_class = HTMLConfluenceTranslator
AttributeError: can't set attribute
```

I am using Sphinx 1.6.5

**Comment by spyoungtech** [comment]
fixed in #16
