### ISSUE TITLE
AttributeError: 'StandaloneHTMLBuilder' object has no attribute 'has_title'

### ISSUE THREAD

**Issue by butorov** [Arello-Mobile/sphinx-confluence#2]
Hello!
I receive a error when I trying to convert our documentation with your plugin. May be this log will help you to find a problem:

```
# Sphinx version: 1.3.3
# Python version: 2.7.5+ (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   /home/shmele/project/src/docs/source/modules/one/forms.rst:: WARNING: document isn't included in any toctree
#   /home/shmele/project/src/docs/source/modules/one/models.rst:: WARNING: document isn't included in any toctree
#   /home/shmele/project/src/docs/source/modules/one/reports.rst:: WARNING: document isn't included in any toctree
#   /home/shmele/project/src/docs/source/modules/two.rst:: WARNING: document isn't included in any toctree
#   /home/shmele/project/src/docs/source/modules/three.rst:: WARNING: document isn't included in any toctree
#   /home/shmele/project/src/docs/source/modules/four.rst:: WARNING: document isn't included in any toctree
#   done
#   preparing documents...
#   done
#   writing output... [  6%] glossary
# Loaded extensions:
#   sphinx.ext.autodoc (1.3.3) from /home/shmele/project/local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.3.3) from /home/shmele/project/local/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.doctest (1.3.3) from /home/shmele/project/local/lib/python2.7/site-packages/sphinx/ext/doctest.pyc
#   alabaster (0.7.6) from /home/shmele/project/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.viewcode (1.3.3) from /home/shmele/project/local/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.coverage (1.3.3) from /home/shmele/project/local/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.todo (1.3.3) from /home/shmele/project/local/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx_confluence (unknown version) from /home/shmele/project/local/lib/python2.7/site-packages/sphinx_confluence/__init__.pyc
Traceback (most recent call last):
  File "/home/shmele/project/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 240, in main
    app.build(opts.force_all, filenames)
  File "/home/shmele/project/local/lib/python2.7/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/home/shmele/project/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 252, in build_update
    'out of date' % len(to_build))
  File "/home/shmele/project/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 323, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/shmele/project/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 361, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/shmele/project/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 369, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/shmele/project/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 439, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/shmele/project/local/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/shmele/project/local/lib/python2.7/site-packages/sphinx/writers/html.py", line 53, in translate
    self.document.walkabout(visitor)
  File "/home/shmele/project/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/shmele/project/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/shmele/project/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/shmele/project/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/shmele/project/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/shmele/project/local/lib/python2.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/home/shmele/project/local/lib/python2.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/shmele/project/local/lib/python2.7/site-packages/sphinx_confluence/__init__.py", line 258, in visit_reference
    if node.get('internal') and self.builder.has_title(self.document):
AttributeError: 'StandaloneHTMLBuilder' object has no attribute 'has_title'
```

It my first time, when I trying to use your extension.

**Comment by n-elloco** [comment]
Do you set builder `json_conf` with parameter `-b`?

Quote from documentation

> Plugin has own Builder json_conf
> 
> `sphinx-build -b json_conf -d build/doctrees source build/json`
